//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/stateData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/stateData", IsNullable=false)]
public partial class statedata {
    
    private controlData[] controlDataField;
    
    private mechanismTarget[] mechanismTargetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("controlData")]
    public controlData[] controlData {
        get {
            return this.controlDataField;
        }
        set {
            this.controlDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mechanismTarget")]
    public mechanismTarget[] mechanismTarget {
        get {
            return this.mechanismTargetField;
        }
        set {
            this.mechanismTargetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/stateData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/stateData", IsNullable=false)]
public partial class controlData {
    
    private string identifierField;
    
    private controlDataMode modeField;
    
    private controlDataConstrolServer constrolServerField;
    
    private string proportionalField;
    
    private string integralField;
    
    private string derivativeField;
    
    private string feedforwardField;
    
    private string izoneField;
    
    private string maxaccelerationField;
    
    private string cruisevelocityField;
    
    public controlData() {
        this.modeField = controlDataMode.PERCENT_OUTPUT;
        this.constrolServerField = controlDataConstrolServer.MOTORCONTROLLER;
        this.proportionalField = "0.0";
        this.integralField = "0.0";
        this.derivativeField = "0.0";
        this.feedforwardField = "0.0";
        this.izoneField = "0.0";
        this.maxaccelerationField = "0.0";
        this.cruisevelocityField = "0.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(controlDataMode.PERCENT_OUTPUT)]
    public controlDataMode mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(controlDataConstrolServer.MOTORCONTROLLER)]
    public controlDataConstrolServer constrolServer {
        get {
            return this.constrolServerField;
        }
        set {
            this.constrolServerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0")]
    public string proportional {
        get {
            return this.proportionalField;
        }
        set {
            this.proportionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0")]
    public string integral {
        get {
            return this.integralField;
        }
        set {
            this.integralField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0")]
    public string derivative {
        get {
            return this.derivativeField;
        }
        set {
            this.derivativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0")]
    public string feedforward {
        get {
            return this.feedforwardField;
        }
        set {
            this.feedforwardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0")]
    public string izone {
        get {
            return this.izoneField;
        }
        set {
            this.izoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0")]
    public string maxacceleration {
        get {
            return this.maxaccelerationField;
        }
        set {
            this.maxaccelerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0")]
    public string cruisevelocity {
        get {
            return this.cruisevelocityField;
        }
        set {
            this.cruisevelocityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/stateData")]
public enum controlDataMode {
    
    /// <remarks/>
    PERCENT_OUTPUT,
    
    /// <remarks/>
    VELOCITY_INCH,
    
    /// <remarks/>
    VELOCITY_DEGREES,
    
    /// <remarks/>
    VELOCITY_RPS,
    
    /// <remarks/>
    VOLTAGE,
    
    /// <remarks/>
    CURRENT,
    
    /// <remarks/>
    TRAPEZOID,
    
    /// <remarks/>
    MOTION_PROFILE,
    
    /// <remarks/>
    MOTION_PROFILE_ARC,
    
    /// <remarks/>
    POSITION_DEGREES,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/stateData")]
public enum controlDataConstrolServer {
    
    /// <remarks/>
    MOTORCONTROLLER,
    
    /// <remarks/>
    ROBORIO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/stateData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/stateData", IsNullable=false)]
public partial class mechanismTarget {
    
    private mechanismTargetStateIdentifier stateIdentifierField;
    
    private string controlDataIdentifierField;
    
    private string controlDataIdentifier2Field;
    
    private string valueField;
    
    private string secondValueField;
    
    private mechanismTargetSolenoid solenoidField;
    
    public mechanismTarget() {
        this.stateIdentifierField = mechanismTargetStateIdentifier.UNKNOWN;
        this.solenoidField = mechanismTargetSolenoid.NONE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(mechanismTargetStateIdentifier.UNKNOWN)]
    public mechanismTargetStateIdentifier stateIdentifier {
        get {
            return this.stateIdentifierField;
        }
        set {
            this.stateIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string controlDataIdentifier {
        get {
            return this.controlDataIdentifierField;
        }
        set {
            this.controlDataIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string controlDataIdentifier2 {
        get {
            return this.controlDataIdentifier2Field;
        }
        set {
            this.controlDataIdentifier2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondValue {
        get {
            return this.secondValueField;
        }
        set {
            this.secondValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(mechanismTargetSolenoid.NONE)]
    public mechanismTargetSolenoid solenoid {
        get {
            return this.solenoidField;
        }
        set {
            this.solenoidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/stateData")]
public enum mechanismTargetStateIdentifier {
    
    /// <remarks/>
    INTAKE_OFF,
    
    /// <remarks/>
    INTAKE_ON,
    
    /// <remarks/>
    INTAKE_EXPEL,
    
    /// <remarks/>
    ARM_OFF,
    
    /// <remarks/>
    ARM_UP,
    
    /// <remarks/>
    ARM_DOWN,
    
    /// <remarks/>
    ARM_MOVING_UP,
    
    /// <remarks/>
    ARM_MOVING_DOWN,
    
    /// <remarks/>
    RELEASE_OPEN_OPEN,
    
    /// <remarks/>
    RELEASE_OPEN_CLOSED,
    
    /// <remarks/>
    RELEASE_CLOSED_OPEN,
    
    /// <remarks/>
    RELEASE_CLOSED_CLOSED,
    
    /// <remarks/>
    FLAG_GRAB,
    
    /// <remarks/>
    FLAG_RELEASE,
    
    /// <remarks/>
    EXAMPLE_OFF,
    
    /// <remarks/>
    EXAMPLE_FORWARD,
    
    /// <remarks/>
    EXAMPLE_REVERSE,
    
    /// <remarks/>
    UNKNOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/stateData")]
public enum mechanismTargetSolenoid {
    
    /// <remarks/>
    NONE,
    
    /// <remarks/>
    ON,
    
    /// <remarks/>
    REVERSE,
}
