//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class robot {
    
    private pdp pdpField;
    
    private pcm pcmField;
    
    private pigeon[] pigeonField;
    
    private limelight limelightField;
    
    private chassis chassisField;
    
    private mechanism[] mechanismField;
    
    private camera[] cameraField;
    
    private roborio[] roborioField;
    
    /// <remarks/>
    public pdp pdp {
        get {
            return this.pdpField;
        }
        set {
            this.pdpField = value;
        }
    }
    
    /// <remarks/>
    public pcm pcm {
        get {
            return this.pcmField;
        }
        set {
            this.pcmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pigeon")]
    public pigeon[] pigeon {
        get {
            return this.pigeonField;
        }
        set {
            this.pigeonField = value;
        }
    }
    
    /// <remarks/>
    public limelight limelight {
        get {
            return this.limelightField;
        }
        set {
            this.limelightField = value;
        }
    }
    
    /// <remarks/>
    public chassis chassis {
        get {
            return this.chassisField;
        }
        set {
            this.chassisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mechanism")]
    public mechanism[] mechanism {
        get {
            return this.mechanismField;
        }
        set {
            this.mechanismField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("camera")]
    public camera[] camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("roborio")]
    public roborio[] roborio {
        get {
            return this.roborioField;
        }
        set {
            this.roborioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class pdp {
    
    private uint canIdField;
    
    private pdpType typeField;
    
    public pdp() {
        this.canIdField = ((uint)(0));
        this.typeField = pdpType.CTRE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint canId {
        get {
            return this.canIdField;
        }
        set {
            this.canIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(pdpType.CTRE)]
    public pdpType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum pdpType {
    
    /// <remarks/>
    CTRE,
    
    /// <remarks/>
    REV,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class pcm {
    
    private analogInput analogInputField;
    
    private uint canIdField;
    
    public pcm() {
        this.canIdField = ((uint)(0));
    }
    
    /// <remarks/>
    public analogInput analogInput {
        get {
            return this.analogInputField;
        }
        set {
            this.analogInputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint canId {
        get {
            return this.canIdField;
        }
        set {
            this.canIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class analogInput {
    
    private analogInputType typeField;
    
    private analogInputAnalogId analogIdField;
    
    private string voltageMinField;
    
    private string voltageMaxField;
    
    private string outputMinField;
    
    private string outputMaxField;
    
    public analogInput() {
        this.typeField = analogInputType.PRESSURE_GAUGE;
        this.analogIdField = analogInputAnalogId.Item0;
        this.voltageMinField = "0.0";
        this.voltageMaxField = "5.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(analogInputType.PRESSURE_GAUGE)]
    public analogInputType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(analogInputAnalogId.Item0)]
    public analogInputAnalogId analogId {
        get {
            return this.analogIdField;
        }
        set {
            this.analogIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string voltageMin {
        get {
            return this.voltageMinField;
        }
        set {
            this.voltageMinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("5.0")]
    public string voltageMax {
        get {
            return this.voltageMaxField;
        }
        set {
            this.voltageMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputMin {
        get {
            return this.outputMinField;
        }
        set {
            this.outputMinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputMax {
        get {
            return this.outputMaxField;
        }
        set {
            this.outputMaxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum analogInputType {
    
    /// <remarks/>
    PRESSURE_GAUGE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum analogInputAnalogId {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class pigeon {
    
    private uint canIdField;
    
    private string canBusNameField;
    
    private pigeonType typeField;
    
    private string rotationField;
    
    private pigeonUsage usageField;
    
    public pigeon() {
        this.canIdField = ((uint)(0));
        this.canBusNameField = "rio";
        this.typeField = pigeonType.pigeon1;
        this.rotationField = "0.0";
        this.usageField = pigeonUsage.CENTER_OF_ROTATION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint canId {
        get {
            return this.canIdField;
        }
        set {
            this.canIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("rio")]
    public string canBusName {
        get {
            return this.canBusNameField;
        }
        set {
            this.canBusNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(pigeonType.pigeon1)]
    public pigeonType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(pigeonUsage.CENTER_OF_ROTATION)]
    public pigeonUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum pigeonType {
    
    /// <remarks/>
    pigeon1,
    
    /// <remarks/>
    pigeon2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum pigeonUsage {
    
    /// <remarks/>
    CENTER_OF_ROTATION,
    
    /// <remarks/>
    SHOOTER_CENTER,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class limelight {
    
    private limelightUsage usageField;
    
    private limelightTablename tablenameField;
    
    private string mountingheightField;
    
    private string horizontaloffsetField;
    
    private string mountingangleField;
    
    private limelightRotation rotationField;
    
    private string targetheightField;
    
    private string targetheight2Field;
    
    private limelightDefaultledmode defaultledmodeField;
    
    private limelightDefaultcammode defaultcammodeField;
    
    private limelightStreammode streammodeField;
    
    private limelightSnapshots snapshotsField;
    
    private string crosshairxField;
    
    private string crosshairyField;
    
    private string secondcrosshairxField;
    
    private string secondcrosshairyField;
    
    public limelight() {
        this.usageField = limelightUsage.MAINLIMELIGHT;
        this.tablenameField = limelightTablename.limelight;
        this.horizontaloffsetField = "0.0";
        this.rotationField = limelightRotation.Item00;
        this.defaultledmodeField = limelightDefaultledmode.currentpipeline;
        this.defaultcammodeField = limelightDefaultcammode.vision;
        this.streammodeField = limelightStreammode.sidebyside;
        this.snapshotsField = limelightSnapshots.off;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(limelightUsage.MAINLIMELIGHT)]
    public limelightUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(limelightTablename.limelight)]
    public limelightTablename tablename {
        get {
            return this.tablenameField;
        }
        set {
            this.tablenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mountingheight {
        get {
            return this.mountingheightField;
        }
        set {
            this.mountingheightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string horizontaloffset {
        get {
            return this.horizontaloffsetField;
        }
        set {
            this.horizontaloffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mountingangle {
        get {
            return this.mountingangleField;
        }
        set {
            this.mountingangleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(limelightRotation.Item00)]
    public limelightRotation rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string targetheight {
        get {
            return this.targetheightField;
        }
        set {
            this.targetheightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string targetheight2 {
        get {
            return this.targetheight2Field;
        }
        set {
            this.targetheight2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(limelightDefaultledmode.currentpipeline)]
    public limelightDefaultledmode defaultledmode {
        get {
            return this.defaultledmodeField;
        }
        set {
            this.defaultledmodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(limelightDefaultcammode.vision)]
    public limelightDefaultcammode defaultcammode {
        get {
            return this.defaultcammodeField;
        }
        set {
            this.defaultcammodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(limelightStreammode.sidebyside)]
    public limelightStreammode streammode {
        get {
            return this.streammodeField;
        }
        set {
            this.streammodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(limelightSnapshots.off)]
    public limelightSnapshots snapshots {
        get {
            return this.snapshotsField;
        }
        set {
            this.snapshotsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string crosshairx {
        get {
            return this.crosshairxField;
        }
        set {
            this.crosshairxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string crosshairy {
        get {
            return this.crosshairyField;
        }
        set {
            this.crosshairyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondcrosshairx {
        get {
            return this.secondcrosshairxField;
        }
        set {
            this.secondcrosshairxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondcrosshairy {
        get {
            return this.secondcrosshairyField;
        }
        set {
            this.secondcrosshairyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum limelightUsage {
    
    /// <remarks/>
    MAINLIMELIGHT,
    
    /// <remarks/>
    SECONDARYLIMELIGHT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum limelightTablename {
    
    /// <remarks/>
    limelight,
    
    /// <remarks/>
    limelight2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum limelightRotation {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0.0")]
    Item00,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90.0")]
    Item900,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("180.0")]
    Item1800,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("270.0")]
    Item2700,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum limelightDefaultledmode {
    
    /// <remarks/>
    currentpipeline,
    
    /// <remarks/>
    off,
    
    /// <remarks/>
    blink,
    
    /// <remarks/>
    on,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum limelightDefaultcammode {
    
    /// <remarks/>
    vision,
    
    /// <remarks/>
    drivercamera,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum limelightStreammode {
    
    /// <remarks/>
    sidebyside,
    
    /// <remarks/>
    pipmain,
    
    /// <remarks/>
    pipsecondary,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum limelightSnapshots {
    
    /// <remarks/>
    off,
    
    /// <remarks/>
    twopersec,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class chassis {
    
    private motor[] motorField;
    
    private swervemodule[] swervemoduleField;
    
    private chassisType typeField;
    
    private string wheelDiameterField;
    
    private string wheelBaseField;
    
    private string trackField;
    
    private chassisWheelSpeedCalcOption wheelSpeedCalcOptionField;
    
    private chassisPoseEstimationOption poseEstimationOptionField;
    
    private string maxVelocityField;
    
    private string maxAngularVelocityField;
    
    private string maxAccelerationField;
    
    private string maxAngularAccelerationField;
    
    private string networkTableField;
    
    private string controlFileField;
    
    public chassis() {
        this.typeField = chassisType.TANK;
        this.wheelSpeedCalcOptionField = chassisWheelSpeedCalcOption.ETHER;
        this.poseEstimationOptionField = chassisPoseEstimationOption.EULERCHASSIS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("motor")]
    public motor[] motor {
        get {
            return this.motorField;
        }
        set {
            this.motorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("swervemodule")]
    public swervemodule[] swervemodule {
        get {
            return this.swervemoduleField;
        }
        set {
            this.swervemoduleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(chassisType.TANK)]
    public chassisType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string wheelDiameter {
        get {
            return this.wheelDiameterField;
        }
        set {
            this.wheelDiameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string wheelBase {
        get {
            return this.wheelBaseField;
        }
        set {
            this.wheelBaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string track {
        get {
            return this.trackField;
        }
        set {
            this.trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(chassisWheelSpeedCalcOption.ETHER)]
    public chassisWheelSpeedCalcOption wheelSpeedCalcOption {
        get {
            return this.wheelSpeedCalcOptionField;
        }
        set {
            this.wheelSpeedCalcOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(chassisPoseEstimationOption.EULERCHASSIS)]
    public chassisPoseEstimationOption poseEstimationOption {
        get {
            return this.poseEstimationOptionField;
        }
        set {
            this.poseEstimationOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxVelocity {
        get {
            return this.maxVelocityField;
        }
        set {
            this.maxVelocityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxAngularVelocity {
        get {
            return this.maxAngularVelocityField;
        }
        set {
            this.maxAngularVelocityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxAcceleration {
        get {
            return this.maxAccelerationField;
        }
        set {
            this.maxAccelerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxAngularAcceleration {
        get {
            return this.maxAngularAccelerationField;
        }
        set {
            this.maxAngularAccelerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string networkTable {
        get {
            return this.networkTableField;
        }
        set {
            this.networkTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string controlFile {
        get {
            return this.controlFileField;
        }
        set {
            this.controlFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class motor {
    
    private digitalInput[] digitalInputField;
    
    private motorUsage usageField;
    
    private uint canIdField;
    
    private string canBusNameField;
    
    private string pdpIDField;
    
    private motorType typeField;
    
    private motorInverted invertedField;
    
    private motorSensorInverted sensorInvertedField;
    
    private motorFeedbackDevice feedbackDeviceField;
    
    private string countsPerRevField;
    
    private string gearRatioField;
    
    private motorBrakeMode brakeModeField;
    
    private string followField;
    
    private string peakCurrentDurationField;
    
    private string continuousCurrentLimitField;
    
    private string peakCurrentLimitField;
    
    private motorCurrentLimiting currentLimitingField;
    
    private motorForwardlimitswitch forwardlimitswitchField;
    
    private motorForwardlimitswitchopen forwardlimitswitchopenField;
    
    private motorReverselimitswitch reverselimitswitchField;
    
    private motorReverselimitswitchopen reverselimitswitchopenField;
    
    private string voltageCompensationSaturationField;
    
    private motorVoltageCompensationEnable voltageCompensationEnableField;
    
    public motor() {
        this.usageField = motorUsage.ARM;
        this.canIdField = ((uint)(0));
        this.canBusNameField = "rio";
        this.typeField = motorType.TALONSRX;
        this.invertedField = motorInverted.@false;
        this.sensorInvertedField = motorSensorInverted.@false;
        this.feedbackDeviceField = motorFeedbackDevice.NONE;
        this.countsPerRevField = "0";
        this.gearRatioField = "1";
        this.brakeModeField = motorBrakeMode.@false;
        this.followField = "-1";
        this.currentLimitingField = motorCurrentLimiting.@false;
        this.forwardlimitswitchField = motorForwardlimitswitch.@false;
        this.forwardlimitswitchopenField = motorForwardlimitswitchopen.@true;
        this.reverselimitswitchField = motorReverselimitswitch.@false;
        this.reverselimitswitchopenField = motorReverselimitswitchopen.@true;
        this.voltageCompensationSaturationField = "12.0";
        this.voltageCompensationEnableField = motorVoltageCompensationEnable.@false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("digitalInput")]
    public digitalInput[] digitalInput {
        get {
            return this.digitalInputField;
        }
        set {
            this.digitalInputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorUsage.ARM)]
    public motorUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint canId {
        get {
            return this.canIdField;
        }
        set {
            this.canIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("rio")]
    public string canBusName {
        get {
            return this.canBusNameField;
        }
        set {
            this.canBusNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pdpID {
        get {
            return this.pdpIDField;
        }
        set {
            this.pdpIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorType.TALONSRX)]
    public motorType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorInverted.@false)]
    public motorInverted inverted {
        get {
            return this.invertedField;
        }
        set {
            this.invertedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorSensorInverted.@false)]
    public motorSensorInverted sensorInverted {
        get {
            return this.sensorInvertedField;
        }
        set {
            this.sensorInvertedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorFeedbackDevice.NONE)]
    public motorFeedbackDevice feedbackDevice {
        get {
            return this.feedbackDeviceField;
        }
        set {
            this.feedbackDeviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0")]
    public string countsPerRev {
        get {
            return this.countsPerRevField;
        }
        set {
            this.countsPerRevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("1")]
    public string gearRatio {
        get {
            return this.gearRatioField;
        }
        set {
            this.gearRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorBrakeMode.@false)]
    public motorBrakeMode brakeMode {
        get {
            return this.brakeModeField;
        }
        set {
            this.brakeModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("-1")]
    public string follow {
        get {
            return this.followField;
        }
        set {
            this.followField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string peakCurrentDuration {
        get {
            return this.peakCurrentDurationField;
        }
        set {
            this.peakCurrentDurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string continuousCurrentLimit {
        get {
            return this.continuousCurrentLimitField;
        }
        set {
            this.continuousCurrentLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string peakCurrentLimit {
        get {
            return this.peakCurrentLimitField;
        }
        set {
            this.peakCurrentLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorCurrentLimiting.@false)]
    public motorCurrentLimiting currentLimiting {
        get {
            return this.currentLimitingField;
        }
        set {
            this.currentLimitingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorForwardlimitswitch.@false)]
    public motorForwardlimitswitch forwardlimitswitch {
        get {
            return this.forwardlimitswitchField;
        }
        set {
            this.forwardlimitswitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorForwardlimitswitchopen.@true)]
    public motorForwardlimitswitchopen forwardlimitswitchopen {
        get {
            return this.forwardlimitswitchopenField;
        }
        set {
            this.forwardlimitswitchopenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorReverselimitswitch.@false)]
    public motorReverselimitswitch reverselimitswitch {
        get {
            return this.reverselimitswitchField;
        }
        set {
            this.reverselimitswitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorReverselimitswitchopen.@true)]
    public motorReverselimitswitchopen reverselimitswitchopen {
        get {
            return this.reverselimitswitchopenField;
        }
        set {
            this.reverselimitswitchopenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("12.0")]
    public string voltageCompensationSaturation {
        get {
            return this.voltageCompensationSaturationField;
        }
        set {
            this.voltageCompensationSaturationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(motorVoltageCompensationEnable.@false)]
    public motorVoltageCompensationEnable voltageCompensationEnable {
        get {
            return this.voltageCompensationEnableField;
        }
        set {
            this.voltageCompensationEnableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class digitalInput {
    
    private digitalInputUsage usageField;
    
    private digitalInputDigitalId digitalIdField;
    
    private digitalInputReversed reversedField;
    
    private string debouncetimeField;
    
    public digitalInput() {
        this.usageField = digitalInputUsage.BALL_PRESENT;
        this.digitalIdField = digitalInputDigitalId.Item0;
        this.reversedField = digitalInputReversed.@false;
        this.debouncetimeField = "0.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(digitalInputUsage.BALL_PRESENT)]
    public digitalInputUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(digitalInputDigitalId.Item0)]
    public digitalInputDigitalId digitalId {
        get {
            return this.digitalIdField;
        }
        set {
            this.digitalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(digitalInputReversed.@false)]
    public digitalInputReversed reversed {
        get {
            return this.reversedField;
        }
        set {
            this.reversedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string debouncetime {
        get {
            return this.debouncetimeField;
        }
        set {
            this.debouncetimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum digitalInputUsage {
    
    /// <remarks/>
    INTAKE_OUT,
    
    /// <remarks/>
    INTAKE_IN,
    
    /// <remarks/>
    BALL_PRESENT,
    
    /// <remarks/>
    BALL_TRANSFER_FORWARD,
    
    /// <remarks/>
    BALL_TRANSFER_BACK,
    
    /// <remarks/>
    SHOOTER_HOOD_MIN,
    
    /// <remarks/>
    SHOOTER_HOOD_MAX,
    
    /// <remarks/>
    CLIMBER_BACK,
    
    /// <remarks/>
    CLIMBER_FORWARD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum digitalInputDigitalId {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("20")]
    Item20,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("21")]
    Item21,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("24")]
    Item24,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("25")]
    Item25,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum digitalInputReversed {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorUsage {
    
    /// <remarks/>
    SWERVE_DRIVE,
    
    /// <remarks/>
    SWERVE_TURN,
    
    /// <remarks/>
    DIFFERENTIAL_LEFT_MAIN,
    
    /// <remarks/>
    DIFFERENTIAL_LEFT_FOLLOWER,
    
    /// <remarks/>
    DIFFERENTIAL_RIGHT_MAIN,
    
    /// <remarks/>
    DIFFERENTIAL_RIGHT_FOLLOWER,
    
    /// <remarks/>
    MECANUM_LEFT_FRONT,
    
    /// <remarks/>
    MECANUM_LEFT_BACK,
    
    /// <remarks/>
    MECANUM_RIGHT_FRONT,
    
    /// <remarks/>
    MECANUM_RIGHT_BACK,
    
    /// <remarks/>
    EXAMPLE,
    
    /// <remarks/>
    INTAKE,
    
    /// <remarks/>
    INTAKE_TRANSFER,
    
    /// <remarks/>
    ARM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorType {
    
    /// <remarks/>
    TALONSRX,
    
    /// <remarks/>
    FALCON,
    
    /// <remarks/>
    BRUSHLESS_SPARK_MAX,
    
    /// <remarks/>
    BRUSHED_SPARK_MAX,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorInverted {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorSensorInverted {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorFeedbackDevice {
    
    /// <remarks/>
    NONE,
    
    /// <remarks/>
    INTERNAL,
    
    /// <remarks/>
    QUADENCODER,
    
    /// <remarks/>
    ANALOG,
    
    /// <remarks/>
    TACHOMETER,
    
    /// <remarks/>
    PULSEWIDTHENCODERPOSITION,
    
    /// <remarks/>
    SENSORSUM,
    
    /// <remarks/>
    SENSORDIFFERENCE,
    
    /// <remarks/>
    REMOTESENSOR0,
    
    /// <remarks/>
    REMOTESENSOR1,
    
    /// <remarks/>
    SOFTWAREEMULATEDSENSOR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorBrakeMode {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorCurrentLimiting {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorForwardlimitswitch {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorForwardlimitswitchopen {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorReverselimitswitch {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorReverselimitswitchopen {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum motorVoltageCompensationEnable {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class swervemodule {
    
    private motor[] motorField;
    
    private cancoder cancoderField;
    
    private swervemoduleType typeField;
    
    private string turn_pField;
    
    private string turn_iField;
    
    private string turn_dField;
    
    private string turn_fField;
    
    private string turn_nominal_valField;
    
    private string turn_peak_valField;
    
    private string turn_max_accField;
    
    private string turn_cruise_velField;
    
    public swervemodule() {
        this.typeField = swervemoduleType.LEFT_FRONT;
        this.turn_pField = "0.0";
        this.turn_iField = "0.0";
        this.turn_dField = "0.0";
        this.turn_fField = "0.0";
        this.turn_nominal_valField = "0.0";
        this.turn_peak_valField = "1.0";
        this.turn_max_accField = "0.0";
        this.turn_cruise_velField = "0.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("motor")]
    public motor[] motor {
        get {
            return this.motorField;
        }
        set {
            this.motorField = value;
        }
    }
    
    /// <remarks/>
    public cancoder cancoder {
        get {
            return this.cancoderField;
        }
        set {
            this.cancoderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(swervemoduleType.LEFT_FRONT)]
    public swervemoduleType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string turn_p {
        get {
            return this.turn_pField;
        }
        set {
            this.turn_pField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string turn_i {
        get {
            return this.turn_iField;
        }
        set {
            this.turn_iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string turn_d {
        get {
            return this.turn_dField;
        }
        set {
            this.turn_dField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string turn_f {
        get {
            return this.turn_fField;
        }
        set {
            this.turn_fField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string turn_nominal_val {
        get {
            return this.turn_nominal_valField;
        }
        set {
            this.turn_nominal_valField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("1.0")]
    public string turn_peak_val {
        get {
            return this.turn_peak_valField;
        }
        set {
            this.turn_peak_valField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string turn_max_acc {
        get {
            return this.turn_max_accField;
        }
        set {
            this.turn_max_accField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string turn_cruise_vel {
        get {
            return this.turn_cruise_velField;
        }
        set {
            this.turn_cruise_velField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class cancoder {
    
    private uint canIdField;
    
    private string canBusNameField;
    
    private string offsetField;
    
    private cancoderReverse reverseField;
    
    public cancoder() {
        this.canIdField = ((uint)(0));
        this.canBusNameField = "rio";
        this.offsetField = "0.0";
        this.reverseField = cancoderReverse.@false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint canId {
        get {
            return this.canIdField;
        }
        set {
            this.canIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("rio")]
    public string canBusName {
        get {
            return this.canBusNameField;
        }
        set {
            this.canBusNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(cancoderReverse.@false)]
    public cancoderReverse reverse {
        get {
            return this.reverseField;
        }
        set {
            this.reverseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum cancoderReverse {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum swervemoduleType {
    
    /// <remarks/>
    LEFT_FRONT,
    
    /// <remarks/>
    RIGHT_FRONT,
    
    /// <remarks/>
    LEFT_BACK,
    
    /// <remarks/>
    RIGHT_BACK,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum chassisType {
    
    /// <remarks/>
    TANK,
    
    /// <remarks/>
    MECANUM,
    
    /// <remarks/>
    SWERVE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum chassisWheelSpeedCalcOption {
    
    /// <remarks/>
    WPI,
    
    /// <remarks/>
    ETHER,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2910")]
    Item2910,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum chassisPoseEstimationOption {
    
    /// <remarks/>
    WPI,
    
    /// <remarks/>
    EULERCHASSIS,
    
    /// <remarks/>
    EULERWHEEL,
    
    /// <remarks/>
    POSECHASSIS,
    
    /// <remarks/>
    POSEWHEEL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class mechanism {
    
    private motor[] motorField;
    
    private solenoid[] solenoidField;
    
    private servo[] servoField;
    
    private analogInput[] analogInputField;
    
    private digitalInput[] digitalInputField;
    
    private cancoder[] cancoderField;
    
    private colorsensor colorsensorField;
    
    private mechanismType typeField;
    
    private string networkTableField;
    
    private string controlFileField;
    
    public mechanism() {
        this.typeField = mechanismType.INTAKE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("motor")]
    public motor[] motor {
        get {
            return this.motorField;
        }
        set {
            this.motorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("solenoid")]
    public solenoid[] solenoid {
        get {
            return this.solenoidField;
        }
        set {
            this.solenoidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("servo")]
    public servo[] servo {
        get {
            return this.servoField;
        }
        set {
            this.servoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("analogInput")]
    public analogInput[] analogInput {
        get {
            return this.analogInputField;
        }
        set {
            this.analogInputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("digitalInput")]
    public digitalInput[] digitalInput {
        get {
            return this.digitalInputField;
        }
        set {
            this.digitalInputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cancoder")]
    public cancoder[] cancoder {
        get {
            return this.cancoderField;
        }
        set {
            this.cancoderField = value;
        }
    }
    
    /// <remarks/>
    public colorsensor colorsensor {
        get {
            return this.colorsensorField;
        }
        set {
            this.colorsensorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(mechanismType.INTAKE)]
    public mechanismType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string networkTable {
        get {
            return this.networkTableField;
        }
        set {
            this.networkTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string controlFile {
        get {
            return this.controlFileField;
        }
        set {
            this.controlFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class solenoid {
    
    private solenoidUsage usageField;
    
    private uint canIdField;
    
    private solenoidChannel channelField;
    
    private solenoidReversed reversedField;
    
    public solenoid() {
        this.usageField = solenoidUsage.INTAKE;
        this.canIdField = ((uint)(0));
        this.channelField = solenoidChannel.Item0;
        this.reversedField = solenoidReversed.@false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(solenoidUsage.INTAKE)]
    public solenoidUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint canId {
        get {
            return this.canIdField;
        }
        set {
            this.canIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(solenoidChannel.Item0)]
    public solenoidChannel channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(solenoidReversed.@false)]
    public solenoidReversed reversed {
        get {
            return this.reversedField;
        }
        set {
            this.reversedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum solenoidUsage {
    
    /// <remarks/>
    INTAKE,
    
    /// <remarks/>
    INTAKE2,
    
    /// <remarks/>
    ARM,
    
    /// <remarks/>
    EXAMPLE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum solenoidChannel {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum solenoidReversed {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class servo {
    
    private servoUsage usageField;
    
    private servoPwmId pwmIdField;
    
    private string minAngleField;
    
    private string maxAngleField;
    
    public servo() {
        this.usageField = servoUsage.RELEASE_SERVO;
        this.pwmIdField = servoPwmId.Item0;
        this.minAngleField = "0.0";
        this.maxAngleField = "360.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(servoUsage.RELEASE_SERVO)]
    public servoUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(servoPwmId.Item0)]
    public servoPwmId pwmId {
        get {
            return this.pwmIdField;
        }
        set {
            this.pwmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0.0")]
    public string minAngle {
        get {
            return this.minAngleField;
        }
        set {
            this.minAngleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("360.0")]
    public string maxAngle {
        get {
            return this.maxAngleField;
        }
        set {
            this.maxAngleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum servoUsage {
    
    /// <remarks/>
    RELEASE_SERVO,
    
    /// <remarks/>
    RELEASE_SERVO2,
    
    /// <remarks/>
    FLAG_SERVO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum servoPwmId {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class colorsensor {
    
    private colorsensorPort portField;
    
    public colorsensor() {
        this.portField = colorsensorPort.kOnboard;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(colorsensorPort.kOnboard)]
    public colorsensorPort port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum colorsensorPort {
    
    /// <remarks/>
    kOnboard,
    
    /// <remarks/>
    kMXP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum mechanismType {
    
    /// <remarks/>
    INTAKE,
    
    /// <remarks/>
    ARM,
    
    /// <remarks/>
    RELEASE,
    
    /// <remarks/>
    FLAGARM,
    
    /// <remarks/>
    EXAMPLE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class camera {
    
    private string idField;
    
    private cameraFormat formatField;
    
    private string widthField;
    
    private string heightField;
    
    private string fpsField;
    
    private cameraThread threadField;
    
    public camera() {
        this.idField = "0";
        this.formatField = cameraFormat.KMJPEG;
        this.widthField = "640";
        this.heightField = "480";
        this.fpsField = "30";
        this.threadField = cameraThread.@false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(cameraFormat.KMJPEG)]
    public cameraFormat format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("640")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("480")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("30")]
    public string fps {
        get {
            return this.fpsField;
        }
        set {
            this.fpsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(cameraThread.@false)]
    public cameraThread thread {
        get {
            return this.threadField;
        }
        set {
            this.threadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum cameraFormat {
    
    /// <remarks/>
    KMJPEG,
    
    /// <remarks/>
    KYUYV,
    
    /// <remarks/>
    KRGB565,
    
    /// <remarks/>
    KBGR,
    
    /// <remarks/>
    KGRAY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum cameraThread {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class roborio {
    
    private roborioOrientation orientationField;
    
    public roborio() {
        this.orientationField = roborioOrientation.X_FORWARD_Y_LEFT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(roborioOrientation.X_FORWARD_Y_LEFT)]
    public roborioOrientation orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum roborioOrientation {
    
    /// <remarks/>
    X_FORWARD_Y_LEFT,
    
    /// <remarks/>
    X_LEFT_Y_BACKWARD,
    
    /// <remarks/>
    X_BACKWARD_Y_RIGHT,
    
    /// <remarks/>
    X_RIGHT_Y_FORWARD,
    
    /// <remarks/>
    X_FORWARD_Y_RIGHT,
    
    /// <remarks/>
    X_LEFT_Y_FORWARD,
    
    /// <remarks/>
    X_BACKWARD_Y_LEFT,
    
    /// <remarks/>
    X_RIGHT_Y_BACKWARD,
    
    /// <remarks/>
    X_UP_Y_LEFT,
    
    /// <remarks/>
    X_LEFT_Y_DOWN,
    
    /// <remarks/>
    X_DOWN_Y_RIGHT,
    
    /// <remarks/>
    X_RIGHT_Y_UP,
    
    /// <remarks/>
    X_UP_Y_RIGHT,
    
    /// <remarks/>
    X_LEFT_Y_UP,
    
    /// <remarks/>
    X_DOWN_Y_LEFT,
    
    /// <remarks/>
    X_RIGHT_Y_DOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class pwmultrasonic {
    
    private pwmultrasonicUsage usageField;
    
    private pwmultrasonicPwmId pwmIdField;
    
    public pwmultrasonic() {
        this.usageField = pwmultrasonicUsage.front;
        this.pwmIdField = pwmultrasonicPwmId.Item0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(pwmultrasonicUsage.front)]
    public pwmultrasonicUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(pwmultrasonicPwmId.Item0)]
    public pwmultrasonicPwmId pwmId {
        get {
            return this.pwmIdField;
        }
        set {
            this.pwmIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum pwmultrasonicUsage {
    
    /// <remarks/>
    front,
    
    /// <remarks/>
    back,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum pwmultrasonicPwmId {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class analogultrasonic {
    
    private analogultrasonicUsage usageField;
    
    private analogultrasonicAnalogId analogIdField;
    
    public analogultrasonic() {
        this.usageField = analogultrasonicUsage.front;
        this.analogIdField = analogultrasonicAnalogId.Item0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(analogultrasonicUsage.front)]
    public analogultrasonicUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(analogultrasonicAnalogId.Item0)]
    public analogultrasonicAnalogId analogId {
        get {
            return this.analogIdField;
        }
        set {
            this.analogIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum analogultrasonicUsage {
    
    /// <remarks/>
    front,
    
    /// <remarks/>
    back,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum analogultrasonicAnalogId {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class lidar {
    
    private lidarUsage usageField;
    
    private string inputpinField;
    
    private string triggerpinField;
    
    public lidar() {
        this.usageField = lidarUsage.front;
        this.inputpinField = "0";
        this.triggerpinField = "0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(lidarUsage.front)]
    public lidarUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0")]
    public string inputpin {
        get {
            return this.inputpinField;
        }
        set {
            this.inputpinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("0")]
    public string triggerpin {
        get {
            return this.triggerpinField;
        }
        set {
            this.triggerpinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum lidarUsage {
    
    /// <remarks/>
    front,
    
    /// <remarks/>
    back,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class led {
    
    private ledPwmId pwmIdField;
    
    private string numberField;
    
    public led() {
        this.pwmIdField = ledPwmId.Item0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(ledPwmId.Item0)]
    public ledPwmId pwmId {
        get {
            return this.pwmIdField;
        }
        set {
            this.pwmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum ledPwmId {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class blinkin {
    
    private blinkinUsage usageField;
    
    private blinkinPwmId pwmIdField;
    
    public blinkin() {
        this.usageField = blinkinUsage.front;
        this.pwmIdField = blinkinPwmId.Item0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(blinkinUsage.front)]
    public blinkinUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(blinkinPwmId.Item0)]
    public blinkinPwmId pwmId {
        get {
            return this.pwmIdField;
        }
        set {
            this.pwmIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum blinkinUsage {
    
    /// <remarks/>
    front,
    
    /// <remarks/>
    back,
    
    /// <remarks/>
    top,
    
    /// <remarks/>
    bottom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum blinkinPwmId {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/robot", IsNullable=false)]
public partial class talontach {
    
    private talontachUsage usageField;
    
    private uint canIdField;
    
    private talontachGeneralpin generalpinField;
    
    public talontach() {
        this.usageField = talontachUsage.Item0;
        this.canIdField = ((uint)(0));
        this.generalpinField = talontachGeneralpin.Item0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(talontachUsage.Item0)]
    public talontachUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint canId {
        get {
            return this.canIdField;
        }
        set {
            this.canIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(talontachGeneralpin.Item0)]
    public talontachGeneralpin generalpin {
        get {
            return this.generalpinField;
        }
        set {
            this.generalpinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum talontachUsage {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/robot")]
public enum talontachGeneralpin {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
}
