//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.732.0 using the following command:
// XmlSchemaClassGenerator.Console --output=..\robotConfiguration --pascal- stateData.xsd
namespace StateData
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.732.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute("statedata", Namespace="http://tempuri.org/stateData", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlRootAttribute("statedata", Namespace="http://tempuri.org/stateData")]
    public partial class statedata
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<controlData> _controlData;
        
        [System.Xml.Serialization.XmlElementAttribute("controlData")]
        public System.Collections.ObjectModel.Collection<controlData> controlData
        {
            get
            {
                return _controlData;
            }
            private set
            {
                _controlData = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the controlData collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool controlDataSpecified
        {
            get
            {
                return (this.controlData.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="statedata" /> class.</para>
        /// </summary>
        public statedata()
        {
            this._controlData = new System.Collections.ObjectModel.Collection<controlData>();
            this._mechanismTarget = new System.Collections.ObjectModel.Collection<mechanismTarget>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<mechanismTarget> _mechanismTarget;
        
        [System.Xml.Serialization.XmlElementAttribute("mechanismTarget")]
        public System.Collections.ObjectModel.Collection<mechanismTarget> mechanismTarget
        {
            get
            {
                return _mechanismTarget;
            }
            private set
            {
                _mechanismTarget = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the mechanismTarget collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mechanismTargetSpecified
        {
            get
            {
                return (this.mechanismTarget.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.732.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute("controlData", Namespace="http://tempuri.org/stateData", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlRootAttribute("controlData", Namespace="http://tempuri.org/stateData")]
    public partial class controlData
    {
        
        //[System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("identifier")]
        public string identifier { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private controlDatamode _mode = StateData.controlDatamode.PERCENT_OUTPUT;
        
        //[System.ComponentModel.DefaultValueAttribute(StateData.controlDatamode.PERCENT_OUTPUT)]
        [System.Xml.Serialization.XmlAttributeAttribute("mode")]
        public controlDatamode mode
        {
            get
            {
                return _mode;
            }
            set
            {
                _mode = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private controlDataconstrolServer _constrolServer = StateData.controlDataconstrolServer.MOTORCONTROLLER;
        
        //[System.ComponentModel.DefaultValueAttribute(StateData.controlDataconstrolServer.MOTORCONTROLLER)]
        [System.Xml.Serialization.XmlAttributeAttribute("constrolServer")]
        public controlDataconstrolServer constrolServer
        {
            get
            {
                return _constrolServer;
            }
            set
            {
                _constrolServer = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _proportional = "0.0";
        
        //[System.ComponentModel.DefaultValueAttribute("0.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("proportional")]
        public string proportional
        {
            get
            {
                return _proportional;
            }
            set
            {
                _proportional = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _integral = "0.0";
        
        //[System.ComponentModel.DefaultValueAttribute("0.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("integral")]
        public string integral
        {
            get
            {
                return _integral;
            }
            set
            {
                _integral = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _derivative = "0.0";
        
        //[System.ComponentModel.DefaultValueAttribute("0.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("derivative")]
        public string derivative
        {
            get
            {
                return _derivative;
            }
            set
            {
                _derivative = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _feedforward = "0.0";
        
        //[System.ComponentModel.DefaultValueAttribute("0.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("feedforward")]
        public string feedforward
        {
            get
            {
                return _feedforward;
            }
            set
            {
                _feedforward = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _izone = "0.0";
        
        //[System.ComponentModel.DefaultValueAttribute("0.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("izone")]
        public string izone
        {
            get
            {
                return _izone;
            }
            set
            {
                _izone = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxacceleration = "0.0";
        
        //[System.ComponentModel.DefaultValueAttribute("0.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("maxacceleration")]
        public string maxacceleration
        {
            get
            {
                return _maxacceleration;
            }
            set
            {
                _maxacceleration = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _cruisevelocity = "0.0";
        
        //[System.ComponentModel.DefaultValueAttribute("0.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("cruisevelocity")]
        public string cruisevelocity
        {
            get
            {
                return _cruisevelocity;
            }
            set
            {
                _cruisevelocity = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.732.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute("controlDatamode", Namespace="http://tempuri.org/stateData", AnonymousType=true)]
    public enum controlDatamode
    {
        
        PERCENT_OUTPUT,
        
        VELOCITY_INCH,
        
        VELOCITY_DEGREES,
        
        VELOCITY_RPS,
        
        VOLTAGE,
        
        CURRENT,
        
        TRAPEZOID,
        
        MOTION_PROFILE,
        
        MOTION_PROFILE_ARC,
        
        POSITION_DEGREES,
        
        POSITION_INCH,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.732.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute("controlDataconstrolServer", Namespace="http://tempuri.org/stateData", AnonymousType=true)]
    public enum controlDataconstrolServer
    {
        
        MOTORCONTROLLER,
        
        ROBORIO,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.732.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute("mechanismTarget", Namespace="http://tempuri.org/stateData", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlRootAttribute("mechanismTarget", Namespace="http://tempuri.org/stateData")]
    public partial class mechanismTarget
    {
        
        //[System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("stateIdentifier")]
        public string stateIdentifier { get; set; }
        
        //[System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("controlDataIdentifier")]
        public string controlDataIdentifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("controlDataIdentifier2")]
        public string controlDataIdentifier2 { get; set; }
        
        //[System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secondValue")]
        public string secondValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private mechanismTargetsolenoid _solenoid = StateData.mechanismTargetsolenoid.NONE;
        
        //[System.ComponentModel.DefaultValueAttribute(StateData.mechanismTargetsolenoid.NONE)]
        [System.Xml.Serialization.XmlAttributeAttribute("solenoid")]
        public mechanismTargetsolenoid solenoid
        {
            get
            {
                return _solenoid;
            }
            set
            {
                _solenoid = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private mechanismTargetsolenoid2 _solenoid2 = StateData.mechanismTargetsolenoid2.NONE;
        
        //[System.ComponentModel.DefaultValueAttribute(StateData.mechanismTargetsolenoid2.NONE)]
        [System.Xml.Serialization.XmlAttributeAttribute("solenoid2")]
        public mechanismTargetsolenoid2 solenoid2
        {
            get
            {
                return _solenoid2;
            }
            set
            {
                _solenoid2 = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.732.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute("mechanismTargetsolenoid", Namespace="http://tempuri.org/stateData", AnonymousType=true)]
    public enum mechanismTargetsolenoid
    {
        
        NONE,
        
        ON,
        
        REVERSE,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.732.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute("mechanismTargetsolenoid2", Namespace="http://tempuri.org/stateData", AnonymousType=true)]
    public enum mechanismTargetsolenoid2
    {
        
        NONE,
        
        ON,
        
        REVERSE,
    }
}
